### ISSUE TITLE
Technical Challenges 

### ISSUE THREAD

**Issue by barnjamin** [Geladen/algorand-games-platform#1]
Hello! Thanks for using Beaker to build this! 

I'd like to address some of the technical challenges you encountered to figure out a good solution.

> The game platform, in multiple cases, requires the user to pass an application call when calling a method of the contract. This application call itself, often takes as parameters additional transactions. To our knowledge, the Beaker framework does not allow the use of its ApplicationClient methods to construct application calls that must be passed as parameters to other application calls. We therefore extended the beaker library (although in a hacky fashion to not slow down development) to support these use cases, adding a nosend version of the corresponding create, call, opt-in and delete methods, together with a finalize function to submit the created application call.

It should be possible to use https://algorand-devrel.github.io/beaker/html/application_client.html#beaker.client.ApplicationClient.add_method_call to build up multiple calls to the contract as part of a group transaction. The AtomicTransactionComposer's `build_group` can also be used to return a list of transactions that could be passed as arguments. Does this meet the needs for the issues you encountered here? Or if not, can you point me to an example?

> Furthermore, we found out (by trial error, as the documentation is still very partial) that it is not possible to have more than one opt_in/delete method per contract. Although this seems like a design decision, we found this limit overly restrictive, and we think that it has impacted the tidiness of our implementation.

Its not possible to have multiple `Bare` methods that listen only for opt_ins since there would be no way to determine which should be routed too without using a method selector. In order to route to multiple methods that are looking for OptIn you can use the `@opt_in` decorator as long as you have arguments (this makes them !bare and provides a method selector for routing) or use the `@external(method_config=MethodConfig(opt_in=CallConfig.Call))`. Both of these are far from obvious esp with light docs

> Lastly, we would've liked to use the new opcodes block and vrf_verify for the implementation of the blackjack contract, but we quickly found ourselves lost, although we're sure that if we had dedicated more time to it, we would've figured it out.

Check out https://github.com/algorand-devrel/coin-flipper if you've not seen it yet for use of the oracle 
Source of data for the oracle is from an instance of https://github.com/ori-shem-tov/vrf-oracle

**Comment by petitnau** [comment]
Hey @barnjamin! Thanks for taking the time to write this, we really appreciate it. Sorry for getting back to you so late :)

> Its not possible to have multiple Bare methods that listen only for opt_ins since there would be no way to determine which should be routed too without using a method selector. In order to route to multiple methods that are looking for OptIn you can use the @opt_in decorator as long as you have arguments (this makes them !bare and provides a method selector for routing) or use the @external(method_config=MethodConfig(opt_in=CallConfig.Call)). Both of these are far from obvious esp with light docs

We had tried to do something like that after taking a look at the source, but it ended up not working and giving us a `pyteal.TealInputError: Multiple opt in methods specified` error. Maybe we are doing something wrong? Here is a minimal example

```py
from pyteal import *
from beaker import *

class Test(Application):
    @external(method_config=MethodConfig(opt_in=CallConfig.CALL))
    def opt1(self, txn: abi.AssetTransferTransaction, amount: abi.Uint64):
        return Seq(Assert(txn.asset_amount() == amount.get()))
    
    @external(method_config=MethodConfig(opt_in=CallConfig.CALL))
    def opt2(self, txn: abi.AssetTransferTransaction, amount: abi.Uint64):
        return Seq(Assert(txn.asset_amount() == amount.get()))
        
Test()
```

> It should be possible to use https://algorand-devrel.github.io/beaker/html/application_client.html#beaker.client.ApplicationClient.add_method_call to build up multiple calls to the contract as part of a group transaction. The AtomicTransactionComposer's build_group can also be used to return a list of transactions that could be passed as arguments. Does this meet the needs for the issues you encountered here? Or if not, can you point me to an example?

In other cases, such as when an application call takes as a parameter a transactions (e.g. a payment), it is possible to write statements such as:
```py
appclient.call(App.fun, alice.pk, txn=PAY_TXN)
```
We think that it would be nice to see something for passing application calls to other application calls in a similar manner: 
```py
appclient.call(App.fun1, alice.pk, txn=appclient2.call_nosend(App2.fun2, alice.pk, txn=PAY_TXN))
```
Of course there might be reasons not to do this, but enabling application calls to be represented as parameters in beaker classes, but not being able to treat them as other parameters are felt a bit clunky to use.

**Comment by barnjamin** [comment]
I filed a PR to address the first one, the reason it'd errored previously was that the app client tries to be smart about allowing a call to things like `opt_in` but if you have multiple it'd get confused. 

I think its probably fine to _unset_ the method if there is >1 with the downside that you'd not be able to call the app clients `opt_in` method directly. 

The other one I also agree with, I'd like to find a nicer way to do this but requires some careful thought since an app call may also take args that are transactions, so I'm not sure what we'd set as the value. 

The `add_method_call` of the app client I think provides the base functionality but it could definitely be improved. If you end up doing more with Beaker and come up with ideas on it please feel free to file an issue or PR.

Thanks again for the feedback!
